/*
  SQL SCHEMA FOR SUPABASE
  
  -- 1. Profiles Table
  CREATE TABLE profiles (
    id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    full_name TEXT,
    email TEXT,
    role TEXT CHECK (role IN ('admin', 'guru', 'staff')),
    created_at TIMESTAMPTZ DEFAULT NOW()
  );

  -- 2. Students Table
  CREATE TABLE students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nis TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    class TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
  );

  -- 3. Employee Attendance
  CREATE TABLE attendance_employees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users NOT NULL,
    status TEXT CHECK (status IN ('hadir', 'izin', 'sakit')),
    type TEXT CHECK (type IN ('masuk', 'pulang')),
    location TEXT,
    timestamp TIMESTAMPTZ DEFAULT NOW()
  );

  -- 4. Student Attendance
  CREATE TABLE attendance_students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT REFERENCES students NOT NULL,
    teacher_id UUID REFERENCES auth.users NOT NULL,
    status TEXT CHECK (status IN ('hadir', 'izin', 'sakit', 'alpha')),
    date DATE DEFAULT CURRENT_DATE,
    created_at TIMESTAMPTZ DEFAULT NOW()
  );

  -- RLS (Row Level Security) - Basic Example
  ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
  CREATE POLICY "Users can view their own profile" ON profiles FOR SELECT USING (auth.uid() = id);
  CREATE POLICY "Admins can view all profiles" ON profiles FOR ALL USING (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
  );
*/
